name: sync-dev
on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Merge main to dev
        # Don't run in forked repository
        if: ${{ github.event.repository.owner.login == 'ByteLegendQuest' }}
        run: >
          git config user.name ByteLegendBot &&
          git config user.email bot@bytelegend.com &&
          git switch -c dev origin/dev &&
          git merge origin/main -m 'Sync with main' &&
          git push https://${{ secrets.BYTELEGENDBOT_TOKEN }}@github.com/${{ github.event.repository.full_name }}.git 'HEAD:dev'
